# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e9531a7e22b3a2235f6bbe2d9ee28ff3"
name = "product-badge-indicator"
application_url = "https://product-inventory-app-five.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # [[webhooks.subscriptions]]
  # topics = ["orders/create"]
  # uri = "/webhooks/orders-create"
  [[webhooks.subscriptions]]
topics = ["products/create"]
uri = "/webhooks/products-create"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks/products-update"

[[webhooks.subscriptions]]
topics = ["products/delete"]
uri = "/webhooks/products-delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_inventory,read_locations,read_orders,read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
